"""Portable notebook session archive manifest contracts."""

from src.session_archive.manifest import (
    SESSION_ARCHIVE_MANIFEST_SCHEMA_VERSION,
    SessionArchiveBoundaries,
    SessionArchiveDuckDBSnapshot,
    SessionArchiveError,
    SessionArchiveLogicalGroup,
    SessionArchiveManifest,
    SessionArchiveRestoreExpectations,
    SessionArchiveShard,
    manifest_to_deterministic_json,
    validate_session_archive_manifest,
    write_session_archive_manifest,
)
from src.session_archive.writer import (
    DEFAULT_EXCLUDE_PATTERNS,
    DEFAULT_MAX_ENTRIES_PER_SHARD,
    DEFAULT_MAX_SHARD_SIZE_BYTES,
    SUPPORTED_COLLISION_POLICIES,
    SessionArchiveIncludePolicy,
    SessionArchivePlan,
    SessionArchiveShardEntry,
    SessionArchiveShardPlan,
    SessionArchiveWriteRequest,
    SessionArchiveWriteResult,
    build_session_archive_plan,
    write_session_archive_pack,
)

__all__ = [
    "DEFAULT_EXCLUDE_PATTERNS",
    "DEFAULT_MAX_ENTRIES_PER_SHARD",
    "DEFAULT_MAX_SHARD_SIZE_BYTES",
    "SESSION_ARCHIVE_MANIFEST_SCHEMA_VERSION",
    "SUPPORTED_COLLISION_POLICIES",
    "SessionArchiveBoundaries",
    "SessionArchiveDuckDBSnapshot",
    "SessionArchiveError",
    "SessionArchiveIncludePolicy",
    "SessionArchiveLogicalGroup",
    "SessionArchiveManifest",
    "SessionArchivePlan",
    "SessionArchiveRestoreExpectations",
    "SessionArchiveShard",
    "SessionArchiveShardEntry",
    "SessionArchiveShardPlan",
    "SessionArchiveWriteRequest",
    "SessionArchiveWriteResult",
    "build_session_archive_plan",
    "manifest_to_deterministic_json",
    "validate_session_archive_manifest",
    "write_session_archive_pack",
    "write_session_archive_manifest",
]
