# These funding links appear under the GitHub "Sponsor" button.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: christophermoverton
ko_fi: christophermoverton

custom:
  - "https://github.com/sponsors/christophermoverton"
  - "https://christophermoverton.github.io/resume-app/"
